# Generated by Django 3.1.2 on 2020-10-28 23:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='username', max_length=200, unique=True)),
                ('user_email', models.CharField(default='email', max_length=400)),
                ('user_password', models.CharField(default='password', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(default='contactemail', max_length=300, unique=True)),
                ('contact_firstName', models.CharField(default='first', max_length=200)),
                ('contact_last_name', models.CharField(default='last', max_length=300)),
                ('contact_phoneNumber', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None)),
                ('contact_address', models.TextField(default='address')),
                ('conact_relation', models.CharField(default='relation', max_length=200)),
                ('contact_group', models.CharField(default='group', max_length=300)),
                ('contact_age', models.CharField(default='age', max_length=5)),
                ('contact_notes', models.TextField(default='notes')),
                ('contact_user', models.ManyToManyField(to='address.User')),
            ],
        ),
    ]
