# Generated by Django 3.1.2 on 2020-10-24 19:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='username', max_length=200)),
                ('userEmail', models.CharField(default='email', max_length=400)),
                ('password', models.CharField(default='password', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEmail', models.CharField(default='contactemail', max_length=300)),
                ('firstName', models.CharField(default='first', max_length=200)),
                ('lastName', models.CharField(default='last', max_length=300)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None)),
                ('contactAddress', models.TextField(default='address')),
                ('relation', models.CharField(default='relation', max_length=200)),
                ('group', models.CharField(default='group', max_length=300)),
                ('age', models.CharField(default='age', max_length=5)),
                ('notes', models.TextField(default='notes')),
                ('user', models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='address.user')),
            ],
        ),
    ]
