# Generated by Django 3.1.2 on 2020-10-23 23:38

import address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.CharField(default='owner', max_length=200, verbose_name=address.models.User),
        ),
    ]
