# Generated by Django 3.1.2 on 2020-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(default='owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='address.user'),
        ),
    ]
