# Generated by Django 3.1.2 on 2020-10-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20201028_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='conact_relation',
            new_name='contact_relation',
        ),
    ]
