# Generated by Django 3.1.2 on 2020-10-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20201024_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default='butterfly1of4', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='address.user'),
        ),
    ]
