# Generated by Django 3.1.2 on 2020-10-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20201024_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
